<?php

namespace AppBundle\Repository;

/**
 * IssuesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssuesRepository extends \Doctrine\ORM\EntityRepository
{
}
